version: '3'

services:
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'

  backend:
    build:
      context: backlog-backend
    volumes:
      - ./backlog-backend:/usr/src/app
      - ./backlog-backend/vendor/bundle:/usr/local/bundle
    ports:
      - '8080:8080'
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_PORT: 3306
      DB_HOST: db
      RAILS_MAX_THREADS: 5
      RAILS_ENV: development

  frontend:
    build:
      context: backlog-frontend
    volumes:
      - ./backlog-frontend:/usr/src/app
    ports:
      - '3000:3000'
